# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlopslite #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 0004
  location: westeurope
  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: false



  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # Compute target for pipeline
  training_target: cpu-cluster
  training_target_sku: STANDARD_D2_V2
  training_target_min_nodes: 0
  training_target_max_nodes: 4
  training_target_tier: dedicated


  # DO NOT TOUCH

  # For pipeline reference
  resource_group: rg-$(namespace)-$(postfix)-$(environment)
  aml_workspace: mlw-$(namespace)-$(postfix)-$(environment)

